set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_C_COMPILER /home/idk/mxe/usr/x86_64-pc-linux-gnu/bin/i686-w64-mingw32.static-gcc)
set(CMAKE_CXX_COMPILER /home/idk/mxe/usr/x86_64-pc-linux-gnu/bin/i686-w64-mingw32.static-g++)
set(CMAKE_RC_COMPILER /home/idk/mxe/usr/bin/i686-w64-mingw32.static-windres)
set(CMAKE_FIND_ROOT_PATH /mxe/usr/i686-w64-mingw32.static)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)


#set(CMAKE_SYSTEM_NAME Windows)
#set(CMAKE_C_COMPILER /home/idk/mxe/usr/bin/i686-w64-mingw32.static-gcc)
#set(CMAKE_CXX_COMPILER /home/idk/mxe/usr/bin/i686-w64-mingw32.static-g++)
#set(CMAKE_RC_COMPILER /home/idk/mxe/usr/bin/i686-w64-mingw32.static-windres)
#set(CMAKE_FIND_ROOT_PATH /home/idk/mxe/usr/i686-w64-mingw32.static/)
#set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
#set(CMAKE_PKG_CONFIG_EXECUTABLE /home/idk/mxe/usr/bin/i686-w64-mingw32.static-pkg-config)
#set(CMAKE_PREFIX_PATH /home/idk/mxe/usr/i686-w64-mingw32.static/lib)
#set(CMAKE_C_COMPILER  x86_64-w64-mingw32-gcc-posix)
#set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++-posix)
#set(CMAKE_RC_COMPILER /home/idk/mxe/usr/bin/i686-w64-mingw32.static-windres)
#set(CMAKE_FIND_ROOT_PATH /home/idk/mxe/usr/i686-w64-mingw32.static/)
